spring:
  data:
    mongodb:
      uri: mongodb+srv://nekinci:+Niyazi678+@cluster0.p7nvm.mongodb.net/songchat?retryWrites=true&w=majority
  application:
    name: websocket-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: key123456

server:
  port: 8020

room:
  public:
    id: public@
    name: Herkese Açık
ws:
  secretKey: key123456

queue:
  mail:
    name: console-consumer-que

exchange:
  name: abc

routingKey:
  mail:
    name: email

cache:
  expirations:
    user: 7200