spring:
  data:
    mongodb:
      uri: mongodb+srv://nekinci:+Niyazi678+@cluster0.p7nvm.mongodb.net/songchat?retryWrites=true&w=majority
jwt:
  secret: key123456

server:
  port: 8081

room:
  public:
    id: public@
    name: Herkese Açık
ws:
  secretKey: key123456

queue:
  mail:
    name: console-consumer-que

exchange:
  name: abc

routingKey:
  mail:
    name: email